export default [
    {
        id:1,
        name:'programming',
        icon:'/coding.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/lotus1.webp',
        promp:''
    },
    {
        id:3,
        name:'creative',
        icon:'coding1.png',
        promp:''
    },
]
//hello